import Head from 'next/head';
import Image from 'next/image';
import FotoSimSTNK from '../../components/sim&stnk/fotoSimSTNK';
import SimStnk from '../../components/sim&stnk/SimStnk';

export default function index() {
  return (
    <div className="">
      <Head>
        <title>Foto SIM & STNK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <SimStnk />
        {/* <FotoSimSTNK /> */}
      </div>
    </div>
  );
}
